backend:
  name: git-gateway
  branch: master

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "homepage"
    label: "Homepage"
    folder: "src/pages/homepage"
    create: false
    fields:
      - label: "Hero Image"
        name: "hero"
        widget: "object"
        required: true
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - label: "Featured Link"
        name: "feature"
        widget: "object"
        required: false
        fields:
          - {label: "Show Featured Link", name: "show", widget: "boolean", default: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}


  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display On Homepage", name: "homepage", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Hero Image", name: "heroimage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events"
    label: "Events"
    folder: "src/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "date"}
      - {label: "Optional Link", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "footer"
    label: "Site Footer"
    folder: "src/components/footer"
    create: false
    fields:
      - label: "Contact Info"
        name: "contact"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: true}
          - {label: "Phone", name: "phone", widget: "string"}
      - {label: "Mailchimp Signup List Url", name: "mailchimp", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}