backend:
  name: git-gateway
  branch: master

media_folder: "static/files/"
public_folder: "/files"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - name: "site"
        label: "Metadata"
        file: "site/metadata.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Base URL", name: "siteUrl", widget: "string"}
      - name: "footer"
        label: "Site Footer"
        file: "src/components/footer/Footer.md"
        create: false
        fields:
          - label: "Contact Info"
            name: "contact"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string", required: true}
              - {label: "Email", name: "email", widget: "string", required: true}
              - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Mailchimp Signup List Url", name: "mailchimp", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage"
    label: "Homepage"
    folder: "src/pages/homepage"
    create: false
    fields:
      - label: "Hero Image"
        name: "hero"
        widget: "object"
        required: true
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - label: "Featured Link"
        name: "feature"
        widget: "object"
        required: false
        fields:
          - {label: "Show Featured Link", name: "show", widget: "boolean", default: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}


  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "blog"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display On Homepage", name: "homepage", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Hero Image", name: "heroimage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Featured Link"
        name: "feature"
        widget: "object"
        required: false
        fields:
          - {label: "Show Featured Link", name: "show", widget: "boolean", default: false}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Button Style (see https://getbootstrap.com/docs/4.0/components/buttons/)",
              name: "buttonStyle", widget: "string", required: false,
              pattern: '^(btn-)?(outline-)?(primary|secondary|success|danger|warning|info|light|dark|link)$'}
          - {label: "Background Color (see https://developer.mozilla.org/en-US/docs/Web/CSS/background-color)",
              name: "backgroundColor", widget: "string", required: false,
              pattern: '^(\w+|\#[a-f0-9]+|(rgba?|hsla?)\(\s*\d+,\s*\d+\%?,\s*\d+\%?(,\s*[\d\.]+)?\))$'}

  - name: "events"
    label: "Events"
    folder: "src/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "date"}
      - {label: "Optional Link", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
